BHMTOnline/Areas/Admin/Controllers/QuyensController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BHMTOnline.Models;

namespace BHMTOnline.Areas.Admin.Controllers
{
    public class QuyensController : Controller
    {
        private BHMTModel db = new BHMTModel();

        // GET: Admin/Quyens
        public ActionResult Index()
        {
            return View(db.Quyens.ToList());
        }

        // GET: Admin/Quyens/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quyen quyen = db.Quyens.Find(id);
            if (quyen == null)
            {
                return HttpNotFound();
            }
            return View(quyen);
        }

        // GET: Admin/Quyens/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Quyens/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDQuyen,TenQuyen")] Quyen quyen)
        {
            if (ModelState.IsValid)
            {
                db.Quyens.Add(quyen);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(quyen);
        }

        // GET: Admin/Quyens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quyen quyen = db.Quyens.Find(id);
            if (quyen == null)
            {
                return HttpNotFound();
            }
            return View(quyen);
        }

        // POST: Admin/Quyens/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IDQuyen,TenQuyen")] Quyen quyen)
        {
            if (ModelState.IsValid)
            {
                db.Entry(quyen).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(quyen);
        }

        // GET: Admin/Quyens/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Quyen quyen = db.Quyens.Find(id);
            if (quyen == null)
            {
                return HttpNotFound();
            }
            return View(quyen);
        }

        // POST: Admin/Quyens/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Quyen quyen = db.Quyens.Find(id);
            db.Quyens.Remove(quyen);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BHMTOnline/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Luna Shop | Admin</title>
    <link href="~/Content/PagedList.css" rel="stylesheet" />
    <link href="~/Areas/Assets/css/StyleAdmin.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" crossorigin="anonymous"></script>

    <style type="text/css">
        .menu1 {
            color: white;
            padding-left: 20px;
        }
        .title-func a
        {
            text-decoration: none;
            color: #fff;
        }
        .bg-success h3 a{
            text-decoration: none;
        }
        .bg-success {
            background: #0c80fb !important;
        }
    </style>
</head>
<body class="sb-nav-fixed">
    @{ var u = Session["use"] as BHMTOnline.Models.NguoiDung; }
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-success">
        <h3>@Html.ActionLink("Luna Shop", "Index", "Home", new { @class = "menu1" })</h3>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button><!-- Navbar Search-->
        <form method="post" action="~/Search" class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Tìm kiếm..." aria-label="Search" aria-describedby="basic-addon2" />
                <div class="input-group-append">
                    <button class="btn btn-primary" style="background: #ff0000" type="button"><i class="fas fa-search"></i></button>
                </div>
            </div>
        </form>

        <!-- Navbar-->
        <ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <a class="dropdown-item" href="#">Cài đặt</a>@*<a class="dropdown-item" href="#">Activity Log</a>*@
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="~/SignOut" >Đăng xuất</a>
                </div>
            </li>
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav title-func">
                        <div class="sb-sidenav-menu-heading" style="color:white"> <h5>Quản lý</h5></div>
                        <div style="padding-left:20px">
                            @Html.ActionLink("Sản phẩm", "Index", "Home")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Hãng sản xuất", "Index", "HangSanXuats")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Hệ điều hành", "Index", "HeDieuHanhs")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Người dùng", "Index", "NguoiDungs")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Phân quyền", "Index", "Quyens")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Đơn hàng", "Index", "DonDatHangs")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Chi tiết đơn hàng", "Index", "ChiTietDonHangs")
                        </div>
                        <br />
                        <div style="padding-left:20px">
                            @Html.ActionLink("Doanh thu", "Index", "DoanhThu")
                        </div>
                    </div>
                </div>

                <div style="margin-bottom: 20px;" class="sb-sidenav-footer">
                    <div class="small">Đăng nhập bởi:</div>
                    @u.Email
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Healer 2021</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Assets/dist/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Assets/dist/assets/demo/chart-area-demo.js"></script>
    <script src="~/Areas/Assets/dist/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/Areas/Assets/dist/assets/demo/datatables-demo.js"></script>
    
</body>
</html>