BHMTOnline/Models/DonDatHang.cs
namespace BHMTOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("DonDatHang")]
    public partial class DonDatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonDatHang()
        {
            ChiTietDonHangs = new HashSet<ChiTietDonHang>();
        }

        [Key]
        public int MaDDH { get; set; }

        public DateTime? NgayDat { get; set; }

        public DateTime? NgayGiao { get; set; }

        public int? TinhTrang { get; set; }

        public bool? DaThanhToan { get; set; }

        public int MaNguoiDung { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonHang> ChiTietDonHangs { get; set; }

        public virtual NguoiDung NguoiDung { get; set; }
    }
}

BHMTOnline/Areas/Admin/Controllers/DonDatHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BHMTOnline.Models;

namespace BHMTOnline.Areas.Admin.Controllers
{
    public class DonDatHangsController : Controller
    {
        private BHMTModel db = new BHMTModel();

        public ActionResult ChiTiet(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donhang = db.DonDatHangs.Find(id);
            var chitiet = db.ChiTietDonHangs.Include(d => d.SanPham).Where(d => d.MaDDH == id).ToList();
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }

        // GET: Admin/DonDatHangs
        public ActionResult Index(string searchString)
        {
            var links = from l in db.DonDatHangs select l;
            if (!String.IsNullOrEmpty(searchString))
            {
                links = links.Where(s => s.TinhTrang.ToString().Contains(searchString));
            }
            return View(links);
        }

        // GET: Admin/DonDatHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }
            return View(donDatHang);
        }

        // GET: Admin/DonDatHangs/Create
        public ActionResult Create()
        {
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "HoTen");
            return View();
        }

        // POST: Admin/DonDatHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaDDH,NgayDat,NgayGiao,TinhTrang,DaThanhToan,MaNguoiDung")] DonDatHang donDatHang)
        {
            if (ModelState.IsValid)
            {
                db.DonDatHangs.Add(donDatHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "HoTen", donDatHang.MaNguoiDung);
            return View(donDatHang);
        }

        // GET: Admin/DonDatHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "HoTen", donDatHang.MaNguoiDung);
            return View(donDatHang);
        }

        // POST: Admin/DonDatHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaDDH,NgayDat,NgayGiao,TinhTrang,DaThanhToan,MaNguoiDung")] DonDatHang donDatHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donDatHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNguoiDung = new SelectList(db.NguoiDungs, "MaNguoiDung", "HoTen", donDatHang.MaNguoiDung);
            return View(donDatHang);
        }

        // GET: Admin/DonDatHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }
            return View(donDatHang);
        }

        public void DelChiTietDonHang(int? id)
        {
            var chitietdondathang = db.ChiTietDonHangs.Where(s => s.MaDDH.ToString().Contains(id.ToString()) );
            foreach (var item in chitietdondathang)
            {
                db.ChiTietDonHangs.Remove(item);
            }
            
            db.SaveChanges();
        }

        // POST: Admin/DonDatHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DelChiTietDonHang(id);
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            db.DonDatHangs.Remove(donDatHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BHMTOnline/Areas/Admin/Views/DonDatHangs/ChiTiet.cshtml
@model IEnumerable<BHMTOnline.Models.ChiTietDonHang>

@{
    ViewBag.Title = "ChiTiet";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết đơn hàng</h2>

<table class="table">
    <tr>
        <th>
            Sản phẩm
        </th>
        <th>
            Số lượng
        </th>
        <th>
            Đơn giá / 1 sản phẩm
        </th>
        <th>
            Thành tiền
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SanPham.TenSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DonGia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThanhTien)
            </td>
        </tr>
    }

</table>

BHMTOnline/Areas/Admin/Views/DonDatHangs/Create.cshtml
@model BHMTOnline.Models.DonDatHang

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Tạo mới đơn hàng</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NgayDat, "Ngày đặt", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiao, "Ngày giao", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrang, "Tình trạng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhTrang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaThanhToan, "Đã thanh toán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DaThanhToan)
                    @Html.ValidationMessageFor(model => model.DaThanhToan, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNguoiDung, "Mã người dùng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BHMTOnline/Areas/Admin/Views/DonDatHangs/Delete.cshtml
@model BHMTOnline.Models.DonDatHang

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Xóa đơn hàng</h2>

<h3>Bạn có chắc chắn muốn xóa?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           Họ tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.HoTen)
        </dd>

        <dt>
            Ngày đặt
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            Ngày giao
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            Tình trạng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            Đã thanh toán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaThanhToan)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BHMTOnline/Areas/Admin/Views/DonDatHangs/Details.cshtml
@model BHMTOnline.Models.DonDatHang

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Chi tiết đơn hàng</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Họ tên
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.HoTen)
        </dd>

        <dt>
            Ngày đặt
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayDat)
        </dd>

        <dt>
            Ngày giao
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayGiao)
        </dd>

        <dt>
            Tình trạng
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TinhTrang)
        </dd>

        <dt>
            Đã thanh toán
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DaThanhToan)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MaDDH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

BHMTOnline/Areas/Admin/Views/DonDatHangs/Edit.cshtml
@model BHMTOnline.Models.DonDatHang

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Sửa đơn hàng</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDDH)

        <div class="form-group">
            @Html.LabelFor(model => model.NgayDat, "Ngày đặt", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayDat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayDat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayGiao, "Ngày giao", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayGiao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NgayGiao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TinhTrang, "Tình trạng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TinhTrang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TinhTrang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DaThanhToan, "Đã thanh toán", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.DaThanhToan)
                    @Html.ValidationMessageFor(model => model.DaThanhToan, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaNguoiDung, "Mã người dùng", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaNguoiDung", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaNguoiDung, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BHMTOnline/Areas/Admin/Views/DonDatHangs/Index.cshtml
@model IEnumerable<BHMTOnline.Models.DonDatHang>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Danh sách</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @using (Html.BeginForm("Index", "DonDatHangs", FormMethod.Post))
    {
    <p>
        Tình trạng: @Html.TextBox("SearchString") <input type="submit" value="Tìm kiếm" />
    </p>
}
    <p />
    <table class="table">
        <tr>
            <th>
                Mã đơn hàng
            </th>
            <th>
                Họ tên
            </th>
            <th>
                Ngày đặt
            </th>
            <th>
                Ngày giao
            </th>
            <th>
                Tình trạng
            </th>
            <th>
                Thanh toán
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.MaDDH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NguoiDung.HoTen)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayDat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NgayGiao)
        </td>
        <td>
            @if (item.TinhTrang == 1)
            {
                <div style="color:red">Đang chờ xác nhận</div>
            }
            else
            {
                <div style="color:red">Đã giao</div>
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DaThanhToan)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.MaDDH }) |
            @Html.ActionLink("Details", "ChiTiet", new { id = item.MaDDH }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.MaDDH }) |
        </td>
    </tr>
        }

    </table>