BHMTOnline/Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BHMTOnline.Models;
using System.Data;
using System.Data.Entity;

namespace BHMTOnline.Controllers
{
    public class DonHangsController : Controller
    {
        private BHMTModel db = new BHMTModel();
        // GET: Donhangs
        // Hiển thị danh sách đơn hàng
        public ActionResult Index()
        {
            //Kiểm tra đang đăng nhập và hiển thị nội dung đơn hàng
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "User");
            }
            NguoiDung kh = (NguoiDung)Session["use"];
            int maND = kh.MaNguoiDung;
            // Sử dụng Include để tham chiếu đến bảng người dùng để lấy các trường thông tin.
            // Thay vì dùng 2 câu truy vấn thì có thể gộp thành một.
            var donhangs = db.DonDatHangs.Include(d => d.NguoiDung).Where(d => d.MaNguoiDung == maND);
            return View(donhangs.ToList());
        }

        // GET: DonDatHangs/Delete/5
        // Tìm đơn hàng cần xóa và hiển thị 1 view thông tin của đơn hàng cần xóa
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            if (donDatHang == null)
            {
                return HttpNotFound();
            }
            return View(donDatHang);
        }

        // Nếu xóa đơn hàng thực hiện xóa all mã đơn hàng có trong chi tiết đơn hàng trước
        public void DelChiTietDonHang(int? id)
        {
            var chitietdondathang = db.ChiTietDonHangs.Where(s => s.MaDDH.ToString().Contains(id.ToString()));
            foreach (var item in chitietdondathang)
            {
                db.ChiTietDonHangs.Remove(item);
            }

            db.SaveChanges();
        }

        // Nếu hủy đơn hàng thì cập nhật số lượng của sp; khi tình trạng 1 mới được hủy đơn
        public void CapNhatSoLuongKhiHuyDon(int? id)
        {
            var chitietdondathang = db.ChiTietDonHangs.Where(s => s.MaDDH.ToString().Contains(id.ToString()));
            foreach (var item in chitietdondathang)
            {
                int masp = item.MaSP;
                int sl = item.SoLuong;
                SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == masp);
                sp.SoLuong += sl;
            }
            db.SaveChanges();
        }

        // POST: Admin/DonDatHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {           
            DonDatHang donDatHang = db.DonDatHangs.Find(id);
            if(donDatHang.TinhTrang.ToString() == "1")
            {
                CapNhatSoLuongKhiHuyDon(id);
                DelChiTietDonHang(id);
                // Sau khi cập nhật số lượng và xóa chi tiết đơn hàng, ta xóa đơn hàng
                db.DonDatHangs.Remove(donDatHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }   
            return RedirectToAction("Index");
        }

        // GET: Donhangs/Details/5
        //Hiển thị chi tiết đơn hàng
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonDatHang donhang = db.DonDatHangs.Find(id);
            var chitiet = db.ChiTietDonHangs.Include(d => d.SanPham).Where(d => d.MaDDH == id).ToList();
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BHMTOnline/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BHMTOnline.Models;
using System.Web.Mvc;

namespace BHMTOnline.Controllers
{
    public class UserController : Controller
    {
        BHMTModel user = new BHMTModel();
        // GET: User
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangKy(NguoiDung nguoiDung)
        {
            try
            {
                if(nguoiDung.Email != "Admin@gmail.com" && nguoiDung.Email != "nhanvien@gmail.com")
                {
                    nguoiDung.IDQuyen = 2;
                }
                else if(nguoiDung.Email == "nhanvien@gmail.com")
                {
                    nguoiDung.IDQuyen = 3;
                }
                else if (nguoiDung.Email == "Admin@gmail.com")
                {
                    nguoiDung.IDQuyen = 1;
                }
                user.NguoiDungs.Add(nguoiDung);
                user.SaveChanges();
                if (ModelState.IsValid)
                {
                    // Nếu dữ liệu đúng thì gọi đến trang đăng nhập
                    return RedirectToAction("DangNhap"); 
                }
                return View("DangKy");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DangNhap(FormCollection userLogin)
        {
            string userEmail = userLogin["userEmail"].ToString();
            string passWord = userLogin["passWord"].ToString();

            // Check xem có người dùng đó dưới db không? SingleOrDefault là lấy dòng kết quả đầu tiên
            var isLogin = user.NguoiDungs.SingleOrDefault(x => x.Email.Equals(userEmail) && x.MatKhau.Equals(passWord));

            if (isLogin != null)
            {
                // Nếu email là Admin@gmail.com thì chuyển đến trang Admin/Home, actionName là Index
                // Lưu session để truyền đi
                if (userEmail == "Admin@gmail.com")
                {
                    Session["use"] = isLogin;
                    return RedirectToAction("Index", "Admin/Home");
                }
                else if(userEmail == "nhanvien@gmail.com")
                {
                    Session["use"] = isLogin;
                    return RedirectToAction("Index", "Staff/Home");
                }    
                else
                {
                    Session["use"] = isLogin;
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.Fail = "Đăng nhập thất bại";
                return View("DangNhap");
            }
        }
        public ActionResult DangXuat()
        {
            Session["use"] = null;
            return RedirectToAction("Index", "Home");
        }

    }
}

BHMTOnline/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Luna Shop</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @using BHMTOnline.Models

<style type="text/css">
    body {
        background-color: #F0F0F0;
    }

    .navbar-inverse {
        background-color: #0c80fb;
        border-color: #39B54A;
    }

    .top_header {
        background-color: #000;
        float: right;
        color: white;
    }

        .top_header a {
            text-decoration: none;
        }

    .form-inline {
        padding-top: 10px;
        float: right;
    }

    .navbar-inverse .navbar-nav > li > a {
        color: white;
        font-size: x-large;
    }

    .navbar-inverse .navbar-brand {
        color: white;
    }

    .navbar-inverse .navbar-nav > li > a {
        color: white;
        font-size: large;
    }

        .navbar-inverse .navbar-nav > li > a:hover {
            color: black;
        }

    .navbar-brand {
        color: cadetblue;
    }

    .giohang {
        color: white;
    }

    .btn-card a:hover{
        color: #f00;
    }
</style>
</head>

<body>
    @{ var u = Session["use"] as BHMTOnline.Models.NguoiDung; }

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="top_header col-md-12">

            <div class="row">
                @*<div class="col-sm-2"><img class="navbar-brand" src="~/HinhanhSP/logo1.jpg" width="20" height="20" style="padding:0" /></div>*@
                <div class="col-sm-4 col-md-0" style="font-size:large"></div>

                <div class="col-sm-4 col-md-0 btn-card" style="padding-left:250px">
                    @Html.Action("GioHangPartial", "GioHang", new { @class = "giohang" })
                </div>
                @*@Html.Action("GioHangPartial", "GioHang",new { @style = "color:while" })*@
                @{ if (u != null)
                    {
                        <div class="col-sm-4 col-md-0">
                            Xin chào : @u.Email
                            &nbsp;
                            @*@Html.ActionLink("ĐĂNG XUẤT", "DangXuat", "User", new { style = "color:red" })*@
                            <a style="color:red" href="/User/DangXuat"> ĐĂNG XUẤT</a>
                        </div>
                    }
                    else
                    {
                        <div class="col-sm-4 col-md-0">
                            <a style="color:white" href="/User/DangKy"> Đăng ký</a>
                            &nbsp;
                            <a style="color:white" href="/User/DangNhap"> Đăng nhập</a>
                        </div>
                    }
                }

            </div>

        </div>
        <div class="container">

            <div class="navbar-header">
                <img class="navbar-brand" src="~/HinhanhSP/iconheader.jpg" width="50" height="50" style="padding: 2px; border-radius: 25px; " />
                @Html.ActionLink("Luna Shop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav">
                    <li>
                        <a href="#" title="PHUKIEN">
                            @*<span><i class="fas fa-desktop"></i></span>*@
                            <span>Phụ kiện</span>

                        </a>
                    </li>
                    <li>
                        <a href="/Home/Contact" title="LIENHE">
                            @*<span><i class="fas fa-headphones"></i></span>*@
                            <span>Liên hệ</span>

                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "DonHangs")">
                            <span>Đơn hàng</span>
                        </a>
                    </li>
                    <li>

                    </li>

                </ul>
                <form class="form-inline">
                    <input class="form-control mr-sm-2" type="search" placeholder="Tìm kiếm sản phẩm..." aria-label="Search">
                    @*<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>*@
                </form>

            </div>

        </div>
    </div>


    <br>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <div>
            <img class="img-responsive" src="~/HinhanhSP/imgbanner.jpg" />
        </div>
        <br />
    </div>
    <footer class="bg-info" style="background: black; color: white">
        <div class="row" style="padding-left:100px">
            <div class="col-md-3 col-sm-6">
                <h2>Bảo hành</h2>
                <span>Chính sách mua hàng</span>
                <br />
                <span>Chính sách bảo hành</span>
                <br />
                <span>Trung tâm bảo hành</span>
                <br />
                <span>Tra cứu bảo hành</span>
            </div>
            <div class="col-md-3 col-sm-6">
                <h2>Liên kết</h2>
                <span>Tin tức Mobile</span>
                <br />
                <span>Lập trình Web</span>
                <br />
                <span>GenkVN</span>
                <br />
                <span>Dân trí</span>


            </div>
            <div class="col-md-3 col-sm-6">
                <h2>Thông tin</h2>
                <span>Về chúng tôi</span>
                <br />
                <span>Liên hệ</span>
                <br />
                <span>Góp ý</span>
                <br />
                <span>Tra cứu</span>
            </div>
            <div class="col-md-3 col-sm-6">
                <h2>Theo dõi</h2>
                <span>Kênh youtube</span>
                <br />
                <span>Fanpage</span>
                <br />
                <span>Shopee</span>
                <br />
                <span>Group</span>

            </div>
        </div>
        <hr />
        <center> <p class="bg-primary" style="background: #0c80fb;">&copy; @DateTime.Now.Year - Healer</p></center>
    </footer>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>